### ISSUE TITLE
ANTLR grammars

### ISSUE THREAD

**Issue by lorenz** [ProtonMail/gluon#303]
Are the ANTLR grammars for this available somewhere?
They don't seem to be in this repo.

**Comment by jameshoulahan** [comment]
Hi there, thanks for the interest in the repo :) 

We've actually moved away from using ANTLR-generated parsers in this project. ANTLR was really helpful in enabling us to build correct IMAP, Address and Date parsers as quickly as possible, but we've since moved to hand-written parsers for performance reasons.

The last commit that used ANTLR parsers was `9f98ae47a031ad64466e6a098b851d040d82f161`; you'll find the grammars in `internal/parser/grammer`.

**Comment by lorenz** [comment]
Thanks for the explanation and the pointer to the original ANTLR grammars! I was just curious since ANTLR was mentioned in the release blogpost.
